Document collection playbooks
redhat-cop/cloud.azure_ops pull request #49
Opened 2023-08-03 15:49 UTC by abikouo

add documentation for collection playbooks `vmss_migrate.yml`, `webapp.yml` and `webapp_container.yml`

2023-08-08 18:56 UTC, gravesm approved these changes

2023-08-10 22:01 UTC, jillr requested changes
Thanks for this @abikouo.  Mostly some copy nits for casing on product/project/service names.

2023-08-10 22:01 UTC, jillr commented on playbooks/WEBAPP.md
> +  - * **docker_dir**: Path on virtual machine where docker files will be downloaded. Default: `/app/pyapp`
```suggestion
  - * **docker_image**: The name of the Docker image to build. Default: `pywebapp`
  - * **docker_dir**: Path on virtual machine where Docker files will be downloaded. Default: `/app/pyapp`
```

2023-08-14 07:13 UTC, abikouo commented on README.md
> +[cloud.azure_ops.webapp](https://github.com/redhat-cop/cloud.azure_ops/blob/main/playbooks/WEBAPP.md)|A playbook to deploy a web application on azure using virtual machines.
documentation added for this playbook.

2023-08-22 23:48 UTC, jillr approved these changes

2023-08-28 15:39 UTC, merged